config/routes.rb
Rails.application.routes.draw do
  get 'users/show'
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }

  devise_for :admin, controllers: {
    sessions: 'admin/sessions',
      # registrations: 'admin/registrations'
  }

  root to: "communities#index"
  mount ActionCable.server => '/cable'

  resources :communities do
    resources :community_topics
    member do
      post :favorite
      put :un_favorite
      put :approve_community
    end
    collection do
      get :list_favorite_community
      get :list_user_favorite
      get :list_user_wait_to_approve
    end
    resources :community_images, only: %i[show], module: :communities
  end

  resource :profile, only: [:show, :edit, :update] do
    member do
      get :visits
    end
  end
  resources :chatrooms, only: [:index, :show, :create] do
    resources :messages, only: [:create, :destroy]
  end
  resources :users, only: [:show, :destroy] do
    member do
      post :follow
      post :like
      post :block
      put :un_block
    end
    collection do
      get :user_blockers
      get :list_user_wait_to_approve_community
    end

    collection do
      resources :community_notifications, only: %i[index], module: :users do
        put :seen, on: :collection
      end
    end
  end

  resources :list_word_founds

  # add router
  namespace :admin do
    root to: "users#index"

    # resources :dashboard, only: [:index]
    resources :users, only: %i[index destroy]
    resources :communities, only: %i[index destroy]
    resources :messages, only: %i[index]
  end

  namespace :push_notifications do
    post :save_token
    post :destroy_token
  end

  resources :list_favorites, only: [:index] do
    collection do
      get "list_user_favorites"
    end
  end

  resources :community_rooms do
    resources :community_messages, only: [:create]
  end

  resources :notifications

  resources :cancel_memberships, only: [:update] do
    collection do
      post "check_user_for_login"
      put "update_user_active"
    end
  end
end

app/models/chatroom.rb
class Chatroom < ApplicationRecord
  has_many :messages
  belongs_to :user1, foreign_key: :user1_id, class_name: 'User'
  belongs_to :user2, foreign_key: :user2_id, class_name: 'User'
  has_one :last_message, -> { order created_at: :desc }, foreign_key: :chatroom_id, class_name: 'Message'

  acts_as_paranoid

  validate :check_user, on: :create

  scope :list_by_user, -> (user_id) do
    includes(:user1, :user2, :last_message)
        .where('user1_id = ? OR user2_id = ?', user_id, user_id)
  end

  scope :not_blocks, -> (user) do
    block_user_ids = user.block_user_ids

    where.not(user1_id: block_user_ids)
        .where.not(user2_id: block_user_ids)
  end

  def self.check_present(user1_id, user2_id)
    where(user1_id: user1_id, user2_id: user2_id)
        .or(where(user1_id: user2_id, user2_id: user1_id)).first
  end

  private

  def check_user
    chatroom = Chatroom.check_present user1_id, user2_id

    errors.add(:user1_id, "is not exit") if chatroom.present?
  end
end

app/controllers/admin/chatrooms_controller.rb
class Admin::ChatroomsController < Admin::BaseController
  before_action :get_chatroom, except: :index

  def index
    page = params[:page] ? params[:page].to_i : 1
    @chatrooms = Chatroom.includes(:user1, :user2, :last_message).order(:created_at).page(page).per(20)
  end

  def show
    page = params[:page] ? params[:page].to_i : 1
    @messages = @chatroom.messages.order('messages.created_at').page(page).per(20)
  end

  private

  def get_chatroom
    @chatroom = Chatroom.find(params[:id])
  end
end

app/controllers/chatrooms_controller.rb
class ChatroomsController < ApplicationController
  before_action :authenticate_user!

  before_action :get_chatroom, only: :show

  def index
    # @user = current_user

    # chatrooms = Chatroom.not_blocks(@user).list_by_user(@user.id)
    # new_lists = []
    # chatrooms.each_with_index do |chatroom, i|
    #   next if chatroom&.last_message.nil?
    #   new_lists << chatroom if i == 0
    #   if chatroom.last_message.created_at > new_lists.last.last_message.created_at
    #     new_lists << chatroom
    #   else
    #     new_lists.insert(0, chatroom)
    #   end
    # end

    @chatrooms = Chatroom.not_blocks(current_user).list_by_user(current_user.id).includes(:last_message).order('messages.created_at DESC')
  end

  def create
    user_id = params[:user_id]
    @chatroom = Chatroom.check_present current_user.id, user_id

    if @chatroom.nil?
      @chatroom = Chatroom.create!(user1_id: current_user.id, user2_id: user_id.to_i)
    end

    redirect_to chatroom_path(@chatroom)
  end

  def show
    @user = current_user
    last_id = params[:last_id]
    last_time = Time.now
    if last_id
      last_message = Message.find_by(id: last_id)
      last_time = last_message.created_at
    end

    @messages = @chatroom.messages.order_created_at(last_time).reverse
    update_messages(@messages) if @messages.present?
    @count = (@count.present? && @count > 1) ? (@count - 1) : nil

    user1 = @chatroom.user1
    user2 = @chatroom.user2
    if user1 == @user
      @from_user = user1
      @to_user = user2
    else
      @from_user = user2
      @to_user = user1
    end

    @products = Product.get_item_by_user(@to_user.id).order(created_at: :desc)

    @exchange_item = ExchangeItem.where(from_user_id: current_user.id, user_id: @to_user.id, exchange_type: "request_change").last

    respond_to do |format|
      format.html
      format.js
    end
  end

  private

  def get_chatroom
    @chatroom = Chatroom.not_blocks(current_user).list_by_user(current_user.id).find_by(id: params[:id])

    redirect_to root_path if @chatroom.blank?
  end

  def update_messages messages
    messages.each do |msg|
      msg.update!(status: Message.statuses[:read])
    end
  end
end

app/helpers/chatrooms_helper.rb
module ChatroomsHelper
end

app/views/admin/chatrooms/index.html.erb
<% title = 'メッセージ履歴' %>

<div class="content-header">
  <h1>
    <%= title %>
  </h1>
  <ol class="breadcrumb">
    <li><a href="/admin"><i class="fa fa-dashboard"></i> Home</a></li>
    <li class="active"><%= title %></li>
  </ol>
</div>

<div class="content body">
  <div class="container-fluid">
    <div class="row">
      <div class="col-12">
        <div class="box box-primary">
          <div class="box-body">
            <table class="table table-hover text-nowrap table-bordered">
              <thead>
              <tr>
                <th>ID</th>
                <th>ユーザ１</th>
                <th>ユーザ２</th>
                <th>最後のメッセージ</th>
              </tr>
              </thead>
              <tbody>
              <% @chatrooms.each do |chatroom| %>
                <tr>
                  <td><a href="<%= admin_chatroom_path(chatroom) %>"><%= chatroom.id %></a></td>
                  <td><%= chatroom.user1.nickname %></td>
                  <td><%= chatroom.user2.nickname %></td>
                  <td><%= chatroom.last_message.body if chatroom.last_message %></td>
                </tr>
              <% end %>
              </tbody>
            </table>

            <div id="paginator" class="pull-right">
              <%= paginate @chatrooms %>
            </div>
          </div><!-- /.box-body -->
        </div>
      </div>
    </div>
  </div>
</div>

app/views/admin/chatrooms/show.html.erb
<% title = 'メッセージ履歴' %>

<div class="content-header">
  <h1>
    <%= title %>
  </h1>
  <ol class="breadcrumb">
    <li><a href="/admin"><i class="fa fa-dashboard"></i> Home</a></li>
    <li class="active"><%= title %></li>
  </ol>
</div>

<div class="content body">
  <div class="container-fluid">
    <div class="row">
      <div class="col-12">
        <div class="box box-primary">
          <div class="box-body">
            <table class="table table-hover text-nowrap table-bordered">
              <thead>
              <tr>
                <th>ID</th>
                <th>User</th>
                <th>Message</th>
                <th>Time</th>
              </tr>
              </thead>
              <tbody>
              <% @messages.each do |message| %>
                <tr>
                  <td><%= message.id %></td>
                  <td><%= message.user.nickname %></td>
                  <td><%= message.body %></td>
                  <td><%= message.created_at.strftime('%Y/%d/%m %H:%M:%S') %></td>
                </tr>
              <% end %>
              </tbody>
            </table>

            <div id="paginator" class="pull-right">
              <%= paginate @messages %>
            </div>
          </div><!-- /.box-body -->
        </div>
      </div>
    </div>
  </div>
</div>