config/routes.rb
Rails.application.routes.draw do
  get 'users/show'
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }

  devise_for :admin, controllers: {
    sessions: 'admin/sessions',
      # registrations: 'admin/registrations'
  }

  root to: "communities#index"
  mount ActionCable.server => '/cable'

  resources :communities do
    resources :community_topics
    member do
      post :favorite
      put :un_favorite
      put :approve_community
    end
    collection do
      get :list_favorite_community
      get :list_user_favorite
      get :list_user_wait_to_approve
    end
    resources :community_images, only: %i[show], module: :communities
  end

  resource :profile, only: [:show, :edit, :update] do
    member do
      get :visits
    end
  end
  resources :chatrooms, only: [:index, :show, :create] do
    resources :messages, only: [:create, :destroy]
  end
  resources :users, only: [:show, :destroy] do
    member do
      post :follow
      post :like
      post :block
      put :un_block
    end
    collection do
      get :user_blockers
      get :list_user_wait_to_approve_community
    end

    collection do
      resources :community_notifications, only: %i[index], module: :users do
        put :seen, on: :collection
      end
    end
  end

  resources :list_word_founds

  # add router
  namespace :admin do
    root to: "users#index"

    # resources :dashboard, only: [:index]
    resources :users, only: %i[index destroy]
    resources :communities, only: %i[index destroy]
    resources :messages, only: %i[index]
  end

  namespace :push_notifications do
    post :save_token
    post :destroy_token
  end

  resources :list_favorites, only: [:index] do
    collection do
      get "list_user_favorites"
    end
  end

  resources :community_rooms do
    resources :community_messages, only: [:create]
  end

  resources :notifications

  resources :cancel_memberships, only: [:update] do
    collection do
      post "check_user_for_login"
      put "update_user_active"
    end
  end
end

app/models/notification.rb
class Notification < ApplicationRecord
  acts_as_paranoid

  belongs_to :user

  enum like_type: { turn_on_like: 0, turn_off_like: 1}
  enum message_type: { turn_on_message: 0, turn_off_message: 1}
  enum notification_type: { turn_on_notificaton: 0, turn_off_notificaton: 1}
end

app/controllers/notifications_controller.rb
class NotificationsController < ApplicationController
  before_action :authenticate_user!
  before_action :find_or_create_notifications, only: [:index, :update]

  def index
    respond_to do |format|
      format.html
      format.js
    end
  end

  def update
    redirect_to notifications_path() if @notification.update_attributes!(notification_params)
  end

  private

  def find_or_create_notifications
    @notification = Notification.find_or_create_by(user_id: current_user.id)
  end

  def notification_params
    params[:notification][:like_type] = params[:notification][:like_type].to_i
    params[:notification][:message_type] = params[:notification][:message_type].to_i
    params[:notification][:notification_type] = params[:notification][:notification_type].to_i
    params.require(:notification).permit(:like_type, :message_type, :notification_type, :user_id)
  end
end

app/views/notifications/index.html.erb
<header class="page-title">
  <h1>通知設定</h1>
</header>

<%= form_for @notification, url: notification_path(@notification), html: { class: '', method: :put } do |f| %>
  <div class="group-btn-notification">
    <div class="text">新着メッセージがあった時</div>
    <div class="button-switch">
      <input type="checkbox" id="switch-message" class="switch" <%= @notification.message_type == "turn_on_message" ? "checked" : "" %> />
      <%= f.hidden_field :message_type, value: Notification.message_types[@notification.message_type] %>
      <label for="switch-blue" class="lbl-off">Off</label>
      <label for="switch-blue" class="lbl-on">On</label>
    </div>
  </div>

  <div class="group-btn-notification">
    <div class="text">いいね！された時</div>
    <div class="button-switch">
      <input type="checkbox" id="switch-like" class="switch" <%= @notification.like_type == "turn_on_like" ? "checked" : "" %> />
      <%= f.hidden_field :like_type, value: Notification.like_types[@notification.like_type] %>
      <label for="switch-blue" class="lbl-off">Off</label>
      <label for="switch-blue" class="lbl-on">On</label>
    </div>
  </div>

  <div class="group-btn-notification">
    <div class="text">その他の通知</div>
    <div class="button-switch">
      <input type="checkbox" id="switch-notification" class="switch" <%= @notification.notification_type == "turn_on_notificaton" ? "checked" : "" %> />
      <%= f.hidden_field :notification_type, value: Notification.notification_types[@notification.notification_type] %>
      <label for="switch-blue" class="lbl-off">Off</label>
      <label for="switch-blue" class="lbl-on">On</label>
    </div>
  </div>

  <div class="group-btn">
    <%= f.submit "決定", class: 'btn-submit' %>
  </div>
<% end %>