config/routes.rb
Rails.application.routes.draw do
  get 'users/show'
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }

  devise_for :admin, controllers: {
    sessions: 'admin/sessions',
      # registrations: 'admin/registrations'
  }

  root to: "communities#index"
  mount ActionCable.server => '/cable'

  resources :communities do
    resources :community_topics
    member do
      post :favorite
      put :un_favorite
      put :approve_community
    end
    collection do
      get :list_favorite_community
      get :list_user_favorite
      get :list_user_wait_to_approve
    end
    resources :community_images, only: %i[show], module: :communities
  end

  resource :profile, only: [:show, :edit, :update] do
    member do
      get :visits
    end
  end
  resources :chatrooms, only: [:index, :show, :create] do
    resources :messages, only: [:create, :destroy]
  end
  resources :users, only: [:show, :destroy] do
    member do
      post :follow
      post :like
      post :block
      put :un_block
    end
    collection do
      get :user_blockers
      get :list_user_wait_to_approve_community
    end

    collection do
      resources :community_notifications, only: %i[index], module: :users do
        put :seen, on: :collection
      end
    end
  end

  resources :list_word_founds

  # add router
  namespace :admin do
    root to: "users#index"

    # resources :dashboard, only: [:index]
    resources :users, only: %i[index destroy]
    resources :communities, only: %i[index destroy]
    resources :messages, only: %i[index]
  end

  namespace :push_notifications do
    post :save_token
    post :destroy_token
  end

  resources :list_favorites, only: [:index] do
    collection do
      get "list_user_favorites"
    end
  end

  resources :community_rooms do
    resources :community_messages, only: [:create]
  end

  resources :notifications

  resources :cancel_memberships, only: [:update] do
    collection do
      post "check_user_for_login"
      put "update_user_active"
    end
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::BaseController
  before_action :get_user, except: [:index, :destroy_multi_users, :new, :create]

  def index
    page = params[:page] ? params[:page].to_i : 1
    q = params[:q] || ''
    @users = User.search(q).order(created_at: :desc).page(page).per(20)
  end

  def new
    @user = User.new()
  end

  def create
    user = User.with_deleted.find_by(email: sign_up_params[:email])
    ActiveRecord::Base.transaction do
      if user.present?
        user.update!(status: User.statuses[:active])
        reupdate_relation_by_user user
        redirect_to sex_admin_users_path(sex: user.sex), notice: 'success'
      else
        user = User.new(sign_up_params)
        user.image = File.new("#{Rails.root}/public/images/default.jpg")
        user.confirmed_at = Time.zone.now
        if user.save
          redirect_to sex_admin_users_path(sex: user.sex), notice: 'success'
        else
          render :new
        end
      end
    end
  end

  def show
    image_count = @user.user_images.count

    if image_count < 3
      i = image_count
      while i < 3
        @user.user_images.build
        i += 1
      end
    end
  end

  def block
    if @user.deleted_at
      @user.restore(recursive: true)
    else
      @user.destroy
    end

    respond_to do |format|
      format.js
    end
  end

  def update
    if @user.update(user_params)
      if @user.user_images.present?
        @user.image = @user.user_images.first.image
      else
        @user.image = nil
      end
      @user.confirmed_at = Time.zone.now
      @user.save

      redirect_to sex_admin_users_path(sex: @user.sex), notice: 'プロフィールが更新されました。'
    else
      render :show
    end
  end

  def destroy_multi_users
    return unless params[:arr_user_id].size > 0
    users = User.where(id: params[:arr_user_id])
    destroy_users users

    respond_to do |format|
      format.js
    end
  end

  def destroy
    if @user.destroy
      redirect_to admin_users_path, notice: '削除成功'
    end
  end

  private

  def get_user
    @user = User.with_deleted.find(params[:id])
    redirect_to sex_admin_users_path(sex: @user.sex) if @user.email == "master_admin@eventmatching.com"
  end

  def user_params
    birthday = params[:day].to_s + '-' + params[:month].to_s + '-' + params[:year].to_s
    params[:user][:birthday] = birthday

    params.require(:user).permit(
        :nickname, :name, :email, :sex, :birthday, :self_introduction, :blood_type, :siblings, :nationality,
        :birth_place, :residence, :academic, :industry, :height, :industry, :body_type,
        user_images_attributes: [:id, :image, :_destroy]
    )
  end

  def sign_up_params
    birthday = params[:day].to_s + '-' + params[:month].to_s + '-' + params[:year].to_s
    params[:user][:birthday] = birthday

    params.require(:user).permit(:nickname, :email, :password, :password_confirmation, :sex, :residence, :birthday)
  end

  def destroy_users users
    return unless users.size > 0
    users.each do |user|
      ActiveRecord::Base.transaction do
        user.update(status: User.statuses[:inactive])
        destroy_relation_by_user user
      end
    end
  end

  def destroy_relation_by_user user
    return unless user.present?

    user.destroy
    user.user_images.destroy
    user.favorites.destroy
    user.follows.destroy
    user.followers.destroy
    user.messages.destroy
    user.likes.destroy
    user.user_likes.destroy
    user.host_chatrooms.destroy
    user.guest_chatrooms.destroy
    user.visits.destroy
    user.visiters.destroy
    user.blocks.destroy
    user.blockers.destroy
    user.products.destroy
    user.rate_users.destroy
    user.communities.destroy
    user.community_messages.destroy
    user.like_products.destroy
    user.products.destroy
    user.community_topics.destroy
    user.exchange_items.destroy
    user.notification&.destroy
  end

  def reupdate_relation_by_user user
    return unless user.present?

    user.update(deleted_at: nil)
    user.user_images.update_all(deleted_at: nil)
    user.favorites.update_all(deleted_at: nil)
    user.follows.update_all(deleted_at: nil)
    user.followers.update_all(deleted_at: nil)
    user.messages.update_all(deleted_at: nil)
    user.likes.update_all(deleted_at: nil)
    user.user_likes.update_all(deleted_at: nil)
    user.host_chatrooms.update_all(deleted_at: nil)
    user.guest_chatrooms.update_all(deleted_at: nil)
    user.visits.update_all(deleted_at: nil)
    user.visiters.update_all(deleted_at: nil)
    user.blocks.update_all(deleted_at: nil)
    user.blockers.update_all(deleted_at: nil)
    user.products.update_all(deleted_at: nil)
    user.rate_users.update_all(deleted_at: nil)
    user.communities.update_all(deleted_at: nil)
    user.community_messages.update_all(deleted_at: nil)
    user.like_products.update_all(deleted_at: nil)
    user.products.update_all(deleted_at: nil)
    user.community_topics.update_all(deleted_at: nil)
    user.exchange_items.update_all(deleted_at: nil)
    user&.notification&.update(deleted_at: nil)
  end
end

app/controllers/users/community_notifications_controller.rb
class Users::CommunityNotificationsController < ApplicationController
  before_action :authenticate_user!

  def index
    @notifications = current_user.community_notifications.not_seen.order(created_at: :desc)
  end

  def seen
    current_user.community_notifications.not_seen.join_to_event.update_all status: CommunityNotification.statuses[:seen]
  end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  def create
    user = User.with_deleted.find_by(email: sign_up_params[:email])
    if user.present?
      self.resource = user
      resource.assign_attributes(sign_up_params)
      if resource.valid?
        resource.image = File.new("#{Rails.root}/public/images/default.jpg")
        resource.save
        resource.restore(recursive: true)

        sign_in(resource)

        redirect_to after_sign_in_path_for(resource)
      else
        clean_up_passwords resource
        flash[:notice] = flash[:notice].to_a.concat resource.errors.full_messages
        set_minimum_password_length

        # because resource persisted? so build new resource
        build_resource(sign_up_params)
        resource.save

        respond_with resource
      end
    else
      build_resource(sign_up_params)

      resource.image = File.new("#{Rails.root}/public/images/default.jpg")
      resource.save
      yield resource if block_given?
      if resource.persisted?
        if resource.active_for_authentication?
          set_flash_message! :notice, :signed_up
          sign_up(resource_name, resource)
          respond_with resource, location: after_sign_up_path_for(resource)
        else
          set_flash_message! :notice, :"signed_up_but_#{resource.inactive_message}"
          expire_data_after_sign_in!
          redirect_to new_user_session_path
        end
      else
        clean_up_passwords resource
        set_minimum_password_length
        respond_with resource
      end
    end
  end
  
  private

  def sign_up_params
    birthday = params[:day].to_s + '-' + params[:month].to_s + '-' + params[:year].to_s
    params[:user][:birthday] = birthday

    params.require(:user).permit(:nickname, :email, :password, :password_confirmation, :sex, :residence, :birthday)
  end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  def destroy
    signed_out = sign_out(resource_name)
    set_flash_message! :notice, :signed_out if signed_out
    yield if block_given?
    respond_to_on_destroy
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  before_action :get_user
  skip_before_action :get_user, only: [:un_block, :user_blockers, :list_user_wait_to_approve_community]

  def show
    @user.visits.create(visit_user_id: current_user.id)
    @follow = @user.follows.find_by(follow_user_id: current_user.id)
    @like = @user.likes.find_by(like_user_id: current_user.id)
    @next_user = User.find(User.pluck(:id).sample)
    products_exchanges = Product.user_exchange_item(@user.id).order(created_at: :desc)
    products = Product.join_like_products.where(product_user_id: @user.id).order(created_at: :desc)
    communities = @user.communities.order(created_at: :desc).limit(3)
    @data = {products_exchanges: products_exchanges, products: products, communities: communities}
  end

  def destroy
    @user.destroy
    redirect_to destroy_user_session_path
  end

  def follow
    @follow = @user.follows.find_by(follow_user_id: current_user.id)
    if @follow
      @follow.destroy
      @follow = nil
    else
      @follow = @user.follows.create!(follow_user_id: current_user.id)
    end
    @follows_count = @user.follows.count

    respond_to do |format|
      format.js
    end
  end

  def block
    @user.blocks.find_or_create_by(block_user_id: current_user.id)

    redirect_to root_path
  end

  def un_block
    if params[:user_id].present? && params[:is_un_block].present? && params[:is_un_block] == "true"
      block = current_user.blockers.where(user_id: params[:user_id].to_i).first
      block.destroy! if block.present?
    end

    respond_to do |format|
      format.js
    end
  end

  def user_blockers
    page = params[:page] ? params[:page].to_i : 1
    user_ids = current_user.blockers.pluck(:user_id)
    @users = User.join_favorites.where(id: user_ids).page(page).per(50)
  end


  def list_user_wait_to_approve_community
    page = params[:page] ? params[:page].to_i : 1

    @favorites = Favorite.includes(:user, :community).joins(:community)
     .where("favorites.user_id != ? AND favorites.status = ? AND communities.community_user_id = ?", current_user.id, Favorite.statuses[:wait_approve], current_user.id)
     .page(page).per(50)
  end

  private

  def get_user
    @user = User.not_blocks(current_user).find_by(id: params[:id].to_i)
    redirect_to root_path if @user.blank?
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def years
    (1960..2005).to_a.map {|year| ["#{year}年", year]}
  end


  def months
    (1..12).to_a.map {|month| ["#{month}月", month]}
  end

  def days
    (1..31).to_a.map {|day| ["#{day}日", day]}
  end

  def provinces
    User::PROVINCES.each_with_index.map do |province, index|
      [province, index]
    end
  end

  def genders
    [["未設定", ''], ["男性", 1], ["女性", 2]]
  end

  def has_user_wait_to_approve_community user_id
    Favorite.list_user_wait_to_approve_community(user_id).present?
  end
end

app/views/users/_list_user_block.html.erb
<div class="user-block">
  <a class="group-image" href=<%= user_path(user) %>>
    <figure>
      <%= image_tag user.image.url, class: "exchange_image" %>
    </figure>
  </a>
  <div class="user-block-group-name">
    <dl>
      <dt class="user-block-item-name"><%= user&.nickname %></dt>
<!--      <dt class="user-block-item-name age"><%#= user.age %></dt>-->
      <dt class="user-block-item-name"><%= User.get_province(user.residence) if user.residence.present? %></dt>
    </dl>
  </div>
  <div class="user-block-empty"></div>
  <div class="user-block-group-name">
<!--    <i class="fas fa-heart"></i><span style="margin-left: 5px"><%#= user.favorites_count %></span>-->
    <dl>
      <dt style="margin-top: 10px">
        <%= link_to 'ブロック解除', "javascript:void(0)", class: 'block-user-btn', data: {user_id: user.id} %>
      </dt>
    </dl>
  </div>
</div>

app/views/users/_user_wait_approve_community.html.erb
<div class="user-block">
  <a class="group-image" href=<%= user_path(favorite.user) %>>
    <figure>
      <%= image_tag favorite.user.image.url, class: "exchange_image" %>
    </figure>
  </a>
  <div class="user-block-group-name">
    <dl>
      <dt class="user-block-item-name"><%= favorite.user&.nickname %></dt>
      <dt class="user-block-item-name"><%= User.get_province(favorite.user.residence) if favorite.user.residence.present? %></dt>
      <dt class="user-block-item-name"><%= favorite&.community&.name %></dt>
    </dl>
  </div>
  <div class="user-block-empty"></div>
  <div class="user-block-group-name">
    <dl>
      <dt style="margin-top: 10px">
        <%= link_to '承認', approve_community_community_path(id: favorite.community&.id, user_id: favorite.user.id), method: :put,
          class: 'btn-approve-community', data: {user_id: favorite.user.id} %>
      </dt>
      <dt style="margin-top: 20px">
        <%= link_to '拒否', un_favorite_community_path(favorite.community, user_id: favorite.user.id), method: :put, class: 'btn-reject-community' %>
      </dt>
    </dl>
  </div>
</div>

app/views/users/follow.js.erb
<% if @follow %>
  $('.follow-btn').addClass('active');
<% else %>
  $('.follow-btn').removeClass('active');
<% end %>

$('#follows_count').text(<%= @follows_count.to_s %>)

app/views/users/like.js.erb
<% if @like %>
  $('.action-like a').addClass('liked');
  $('.action-like span').text('いいね済み');
  $('.modal-alert-like').css('display', 'block');
<% else %>
  $('.action-like a').removeClass('liked');
  $('.action-like span').text('いいね');
<% end %>

app/views/users/list_user_wait_to_approve_community.html.erb
<header class="page-title">
  <h1>参加申請一覧</h1>
</header>

<% if @favorites.present? %>
  <div id="search_users" class="search-items" data-page="1" data-total="<%= @favorites.total_pages %>">
    <%= render :partial => 'users/user_wait_approve_community', collection: @favorites, as: :favorite %>

    <div id="loading" class="hidden">
      loading....
    </div>
  </div>
<% else %>
  <div style="padding-top: 40vh; text-align: center; background: #fff;">データがありません。</div>
<% end %>

app/views/users/show.html.erb
<header class="page-title">
  <%= link_to :back, class: 'btn-back' do %>
    <i class="fas fa-angle-left"></i>
  <% end %>
  <h1><%= @user.nickname %></h1>
  <div class='absolute-notification'>
    <%= render 'shared/notification' %>
  </div>
  <% if current_user == @user %>
    <a href="javascript:void(0);" class="nav-ellips open-nav">
      <i class="fas fa-bars"></i>
    </a>
  <% else %>
    <a href="javascript:void(0);" class="nav-ellips open-nav" id="open-menu-user">
      <i class="fas fa-bars"></i>
    </a>
  <% end %>
</header>

<% unless @user.user_images.blank? %>
  <section class="profile-gallery">
    <div class="gallery">
      <% @user.user_images.each do |user_image| %>
        <figure>
          <%= image_tag user_image.image.url %>
        </figure>
      <% end %>
    </div>
    <div class="slider-nav"></div>
  </section>
<% else %>
  <section class="profile-gallery">
    <div class="gallery">
      <figure>
        <%= image_tag "/images/original/warashibe_top.png" %>
      </figure>
    </div>
    <div class="slider-nav"></div>
  </section>
<% end %>
<section class="profile-meta">
  <ul>
    <li class="img-profile">
      <%= image_tag @user.image.url, class: "avatar-user" %>
      <% if @user.identification == "identification" %>
        <div class="identify-user"></div>
      <% end %>
    </li>
    <li class="text-meta">
      <h1><%= @user.nickname %></h1>
      <div class="profile-heart"><i class="fas fa-heart"></i><%= @user.likes.count %>人気</div>
    </li>
    <li class="text-meta">
      <p style="text-align: left;padding-bottom: 5px;"><%= User.get_province(@user.residence) %></p>
      <div class="profile-like">
        <span id="follows_count"><%= @user.follows.count %></span>人フォロー中
      </div>
    </li>
    <li class="text-meta">
      <% if current_user != @user %>
        <%#= link_to 'ブロック', "javascript:void(0)", class: 'block-btn', id: "block-user" %>
        <%= button_to 'フォロー',
                      follow_user_path(@user),
                      remote: true,
                      method: :post,
                      class: "follow-btn #{ 'active' if @follow }",
                      type: 'button' %>
      <% end %>
    </li>
  </ul>
</section>
<% if @data[:communities].present? %>
  <section class="profile-community">
    <h2>イベント一覧</h2>
    <%= link_to '全部を見る', communities_path(user_id: @user.id), class: 'view-all' %>
    <ul>
      <% @data[:communities].each do |community| %>
        <li>
          <a href="<%= community_path(community) %>">
            <%= image_tag community.image.url %>
            <p><%= community.name %></p>
          </a>
        </li>
      <% end %>
    </ul>
  </section>
<% end %>
<section class="profile-info">
  <h2>メッセージ</h2>
  <p><%= @user.self_introduction %></p>
</section>
<section class="profile-info">
  <h2>基本情報</h2>
  <table>
    <tr>
      <th>ニックネーム</th>
      <td><%= @user.nickname %></td>
    </tr>
    <tr>
      <th>年齢</th>
      <td><%= @user.age %>歳</td>
    </tr>
    <tr>
      <th>血液型</th>
      <td><%= User.human_enum_name(:blood_type, @user.blood_type) if @user.blood_type %></td>
    </tr>
    <tr>
      <th>居住地</th>
      <td><%= User.get_province(@user.residence) %></td>
    </tr>
  </table>
</section>

<section class="link-social">
  <% if @user&.facebook_url.present? %>
    <%= link_to @user&.facebook_url, target: "_blank" do %>
      <span class="fa fa-facebook" aria-hidden="true"></span>
    <% end %>
  <% end %>

  <% if @user&.instagram_url.present? %>
    <%= link_to @user&.instagram_url, target: "_blank" do %>
      <span class="fa fa-instagram" aria-hidden="true"></span>
    <% end %>
  <% end %>

  <% if @user&.youtube_url.present? %>
    <%= link_to @user&.youtube_url, target: "_blank" do %>
      <span class="fa fa-youtube-square" aria-hidden="true"></span>
    <% end %>
  <% end %>
</section>

<% if current_user != @user %>
  <div class="profile-action">
    <div class="action-item action-comment">
      <%= link_to chatrooms_path(user_id: @user.id), method: :post do %>
        <i class="fa fa-comment-o" aria-hidden="true"></i><br/>
        <span>メッセージ</span>
      <% end %>
    </div>
  </div>
<% else %>
  <div class="center margin-bottom-50">
    <a href="javascript:void(0);" class="btn-edit" id="btn-edit-profie">プロフィール編集</a>
  </div>
<% end %>

<div class="modal-custom modal-alert-like">
  <span class="close close-modal" title="Close Modal">×</span>
  <div class="modal-content">
    <div class="container">
      <p>いいねと同時にメッセージを送りましょう</p><br/><br/>

      <div class="clearfix">
        <button type="button" class="cancelbtn close-modal">Cancel</button>
        <%= button_to chatrooms_path(user_id: @user.id), method: :post, class: 'primarybtn' do %>
          <span>メッセージを送る</span>
        <% end %>
      </div>
    </div>
  </div>
</div>

<% if current_user != @user %>
  <div class="modal-custom modal-alert-block">
    <span class="btn-close-modal close-modal" title="Close Modal">×</span>
    <div class="modal-content">
      <div class="container">
        <h2>ブロックしてよろしいですか？</h2>
        <div class="clearfix">
          <%= button_to block_user_path(user_id: @user.id), method: :post, class: 'primary-btn' do %>
            <span>ブロック</span>
          <% end %>
        </div>
      </div>
    </div>
  </div>

  <%= render 'layouts/modal_check_word_violate' %>
<% end %>

<div class="modal-custom modal-show-avatar-user" id="show-avatar-user">
  <span class="btn-close-modal close-modal" title="Close Modal">×</span>
  <div class="modal-content">
    <div class="container">
      <div class="avatar-user-content">
        <%= image_tag @user&.image.url %>
      </div>
    </div>
  </div>
</div>

app/views/users/user_blockers.html.erb
<header class="page-title">
  <h1>ブロックユーザー一覧</h1>
</header>

<% if @users.present? %>
  <div id="search_users" class="search-items" data-page="1" data-total="<%= @users.total_pages %>">
    <%= render :partial => 'users/list_user_block', collection: @users, as: :user %>

    <div id="loading" class="hidden">
      loading....
    </div>
  </div>
<% else %>
  <div style="margin-top: 40vh; text-align: center;">データがありません。</div>
<% end %>

<div class="modal-custom modal-alert-block-list">
  <span class="close close-modal" title="Close Modal">×</span>
  <form class="modal-content">
    <div class="container">
      <p>ブロック解除してよろしいですか？</p><br/>

      <div class="clearfix">
        <button type="button" class="cancelbtn close-modal">Cancel</button>
        <%= link_to "OK", "javascript:void(0)",class: "confirm-block-btn", id: "block_user", data: {userid: ""} %>
      </div>
    </div>
  </form>
</div>