config/routes.rb
Rails.application.routes.draw do
  get 'users/show'
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }

  devise_for :admin, controllers: {
    sessions: 'admin/sessions',
      # registrations: 'admin/registrations'
  }

  root to: "communities#index"
  mount ActionCable.server => '/cable'

  resources :communities do
    resources :community_topics
    member do
      post :favorite
      put :un_favorite
      put :approve_community
    end
    collection do
      get :list_favorite_community
      get :list_user_favorite
      get :list_user_wait_to_approve
    end
    resources :community_images, only: %i[show], module: :communities
  end

  resource :profile, only: [:show, :edit, :update] do
    member do
      get :visits
    end
  end
  resources :chatrooms, only: [:index, :show, :create] do
    resources :messages, only: [:create, :destroy]
  end
  resources :users, only: [:show, :destroy] do
    member do
      post :follow
      post :like
      post :block
      put :un_block
    end
    collection do
      get :user_blockers
      get :list_user_wait_to_approve_community
    end

    collection do
      resources :community_notifications, only: %i[index], module: :users do
        put :seen, on: :collection
      end
    end
  end

  resources :list_word_founds

  # add router
  namespace :admin do
    root to: "users#index"

    # resources :dashboard, only: [:index]
    resources :users, only: %i[index destroy]
    resources :communities, only: %i[index destroy]
    resources :messages, only: %i[index]
  end

  namespace :push_notifications do
    post :save_token
    post :destroy_token
  end

  resources :list_favorites, only: [:index] do
    collection do
      get "list_user_favorites"
    end
  end

  resources :community_rooms do
    resources :community_messages, only: [:create]
  end

  resources :notifications

  resources :cancel_memberships, only: [:update] do
    collection do
      post "check_user_for_login"
      put "update_user_active"
    end
  end
end

app/models/community_topic.rb
class CommunityTopic < ApplicationRecord
  belongs_to :community
  has_many :community_topic_images, dependent: :destroy
  has_one :community_room, foreign_key: :community_topic_id, class_name: 'CommunityRoom'
  belongs_to :user

  acts_as_paranoid

  accepts_nested_attributes_for :community_topic_images, allow_destroy: true

  validates :title, presence: true

  has_attached_file :image, styles: { medium: "300x300", thumb: "100x100" }
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/
end

app/controllers/community_topics_controller.rb
class CommunityTopicsController < ApplicationController
  before_action :authenticate_user!

  before_action :get_community_topic, only: [:show, :edit, :update, :destroy]

  def new
    @community = Community.find_by(id: params[:community_id])
    @community_topic = CommunityTopic.new()

    image_count = @community_topic.community_topic_images.count

    if image_count < 1
      i = image_count
      while i < 1
        @community_topic.community_topic_images.build
        i += 1
      end
    end
  end

  def create
    ActiveRecord::Base.transaction do
      @community = Community.find_by(id: community_topic_params[:community_id])
      @community_topic = CommunityTopic.new(community_topic_params)
      @community_topic.user_id = current_user.id
      if @community_topic.save
        if @community_topic.community_topic_images.present?
          @community_topic.image = @community_topic.community_topic_images.first.image
        else
          @community_topic.image = current_user&.image
        end
        @community_topic.save

        CommunityRoom.create!(creator_id: current_user.id, community_topic_id: @community_topic.id)

        redirect_to community_community_topic_path(id: @community_topic.id, community_id: @community_topic&.community.id), notice: 'success'
      else
        image_count = @community_topic.community_topic_images.count

        if image_count < 1
          i = image_count
          while i < 1
            @community_topic.community_topic_images.build
            i += 1
          end
        end
        render :new
      end
    end
  end

  def edit
    image_count = @community_topic.community_topic_images.count

    if image_count < 1
      i = image_count
      while i < 1
        @community_topic.community_topic_images.build
        i += 1
      end
    end
  end

  def update
    ActiveRecord::Base.transaction do
      @community_topic.assign_attributes(community_topic_params)
      @community_topic.community_topic_images.each do |community_topic_image|
        community_topic_image.set_image
      end
      if @community_topic.save
        if @community_topic.community_topic_images.present?
          @community_topic.image = @community_topic.community_topic_images.first.image
        else
          @community_topic.image = nil
        end
        @community_topic.save

        redirect_to community_community_topic_path(id: @community_topic.id, community_id: @community_topic&.community.id), notice: 'success'
      else
        render :edit
      end
    end
  end

  def show
    last_time = Time.now
    @community_room = @community_topic&.community_room
    @messages = @community_room.community_messages.order_created_at(last_time).reverse

    community = @community_topic&.community

    @user_join_community = community.users.count_user_join_community(current_user)

    respond_to do |format|
      format.html
      format.js
    end
  end

  def destroy
    if @community_topic.destroy
      redirect_to communities_path(id: params[:community_id]), notice: 'success'
    else
      render :edit
    end
  end

  private

  def get_community_topic
    @community = Community.find_by(id: params[:community_id])
    @community_topic = CommunityTopic.find(params[:id])
    redirect_to communities_path(id: params[:community_id]) if @community_topic.blank?
  end

  def community_topic_params
    params.require(:community_topic).permit(:title, :description, :community_id, :user_id, community_topic_images_attributes: [:id, :image_topic, :_destroy])
  end
end

app/views/community_topics/_topic.html.erb
<% image_url = (community_topic.image.url.present? && community_topic.image.url == "/images/original/missing.png") ?
   @community.image.url : community_topic.image.url %>
<tr>
  <th class="avatar">
    <span class="avatar available">
      <%= link_to community_community_topic_path(community_id: @community.id, id: community_topic.id) do %>
        <%= image_tag image_url, class: 'img-circle' %>
      <% end %>
    </span>
  </th>
  <td class="title">
    <%= link_to community_topic.title, community_community_topic_path(community_id: @community.id, id: community_topic.id) %>
  </td>
  <td class="date">
    <div><%= t('views.communities.show.time_end_number_messages', date: format_short_day(community_topic.created_at)) %></div>
      <%= community_topic&.community&.user&.nickname %>
  </td>
</tr>

app/views/community_topics/edit.html.erb
<script src="https://cdnjs.cloudflare.com/ajax/libs/croppie/2.6.4/croppie.js"></script>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/croppie/2.6.4/croppie.css" />

<div id="top" class="community-detail">
  <%= link_to community_community_topic_path(community_id: @community_topic&.community&.id, id: @community_topic.id), class: 'btn-back' do %>
    <i class="fas fa-chevron-circle-left"></i>
  <% end %>

  <header class="page-title">
    <h1>編集</h1>
  </header>

  <%= form_for @community_topic, url: community_community_topic_path(community_id: @community_topic&.community&.id, id: @community_topic.id),
    html: { class: 'registration-form', method: :put } do |f| %>
    <div class="center error-messages">
      <%= render "layouts/errors_messages", resource: @community_topic %>
    </div>

    <div class="field community-images">
      <div class="text-title">
        <label>画像</label>
      </div>
      <%= f.fields_for :community_topic_images do |p| %>
        <div class="image-field">
          <%= file_field_tag "image", id: "image_field_#{p.index}", class: 'image_field', data: {index: p.index} %>
          <%= p.hidden_field :image_topic, id: "image_field_hidden_#{p.index}", value: "" %>
          <%= p.text_field :_destroy, id: "destroy_image_#{p.index}", class: 'destroy_image', value: !p.object.image.exists? %>
          <span id="remove_<%= p.index %>"
                class="remove <%= 'hidden' unless p.object.image.exists? %>"
                data-index="<%= p.index %>">
            <i class="fa fa-times-circle" aria-hidden="true"></i>
          </span>
          <div class="preview-image" data-index="<%= p.index %>">
            <%= image_tag p.object.image.url, class: 'preview', id: "preview_#{p.index}" %>
          </div>
        </div>
      <% end %>
    </div>

    <div class="field">
      <div class="text-title">
        <label>タイトル</label>
        <label class="required">（※必須）</label>
      </div>
      <%= f.text_field :title, value: f.object.title, class: 'login-type' %>
    </div>

    <!--    <div class="field">-->
    <!--      <label>カテゴリ</label>-->
    <%#= f.select :category, options_for_select(category_list, f.object.category || 0), {}, class: 'login-type' %>
    <!--    </div>-->

    <div class="field">
      <div class="text-title">
        <label>概要</label>
        <label class="required">（※必須）</label>
      </div>
      <%= f.text_area :description, value: f.object.description, class: 'text-area' %>
    </div>

    <%= f.hidden_field :community_id, value: @community_topic&.community&.id %>

    <div class="actions">
      <%= link_to "削除", "#", id: "delete-topic", class: "delete-btn" %>
      <%= f.submit "更新する", class: 'btn-login', id: "create-new-community-topic" %>
    </div>
  <% end %>
</div>

<div class="modal-custom modal-delete-topic">
  <span class="btn-close-modal close-modal" title="Close Modal">×</span>
  <div class="modal-content">
    <div class="container">
      <h2>確認</h2>
      <br>
      <h2>削除してよろしいですか</h2>
      <br>
      <div class="clearfix">
        <button type="button" class="btn-cancel close-modal">キャンセル</button>
        <%= link_to "削除", community_community_topic_path(community_id: @community_topic&.community&.id, id: @community_topic.id), method: :delete,class: "btn-confirm" %>
      </div>
    </div>
  </div>
</div>

<%= render 'layouts/modal_crop_image' %>
<%= render 'layouts/modal_check_word_violate' %>

app/views/community_topics/new.html.erb
<div id="top" class="community-detail">
  <header class="page-title">
    <h1>新規登録</h1>
  </header>

  <%= form_for @community_topic, url: community_community_topics_path(community_id: @community&.id), html: { class: 'registration-form', method: :post } do |f| %>
    <div class="center error-messages">
      <%= render "layouts/errors_messages", resource: @community_topic %>
    </div>

    <div class="field community-images">
      <div class="text-title">
        <label>画像</label>
      </div>
      <%= f.fields_for :community_topic_images do |p| %>
        <div class="image-field">
          <%= file_field_tag "image", id: "image_field_#{p.index}", class: 'image_field', data: {index: p.index} %>
          <%= p.hidden_field :image_topic, id: "image_field_hidden_#{p.index}", value: "" %>
          <%= p.text_field :_destroy, id: "destroy_image_#{p.index}", class: 'destroy_image', value: !p.object.image.exists? %>
          <span id="remove_<%= p.index %>"
                class="remove <%= 'hidden' unless p.object.image.exists? %>"
                data-index="<%= p.index %>">
            <i class="fa fa-times-circle" aria-hidden="true"></i>
          </span>
          <div class="preview-image" data-index="<%= p.index %>">
            <%= image_tag p.object.image.url, class: 'preview', id: "preview_#{p.index}" %>
          </div>
        </div>
      <% end %>
    </div>

    <div class="field">
      <div class="text-title">
        <label>タイトル</label>
        <label class="required">（※必須）</label>
      </div>
      <%= f.text_field :title, value: f.object.title, class: 'login-type' %>
    </div>

<!--    <div class="field">-->
<!--      <label>カテゴリ</label>-->
      <%#= f.select :category, options_for_select(category_list, f.object.category || 0), {}, class: 'login-type' %>
<!--    </div>-->

    <div class="field">
      <div class="text-title">
        <label>概要</label>
        <label class="required">（※必須）</label>
      </div>
      <%= f.text_area :description, value: f.object.description, class: 'text-area' %>
    </div>

    <%= f.hidden_field :community_id, value: @community&.id %>
    <%= f.hidden_field :user_id, value: current_user&.id %>

    <div class="actions">
      <%= f.submit "登録する", class: 'btn-create btn-disabled', id: "create-new-community-topic", disabled: true %>
    </div>
  <% end %>
</div>

<%= render 'layouts/modal_crop_image' %>
<%= render 'layouts/modal_check_word_violate' %>

app/views/community_topics/show.html.erb
<header class="page-title">
  <%= link_to community_path(@community_topic&.community), class: 'btn-back' do %>
    <i class="fas fa-angle-left"></i>
  <% end %>
  <h1><%= @community_topic.title %></h1>
  <% if @community_topic&.user_id == current_user.id %>
    <%= link_to edit_community_community_topic_path(id: @community_topic&.id, community_id: @community_topic&.community&.id), class: 'btn-edit-comunity' do %>
      <i class="fa fa-pencil" aria-hidden="true"></i>
    <% end %>
  <% end %>
</header>

<div class="field product-images">
  <% unless @community_topic.image.blank? %>
    <section class="profile-gallery">
      <div class="gallery">
        <figure>
          <%= image_tag @community_topic.image.url %>
        </figure>
      </div>
      <div class="slider-nav"></div>
    </section>
  <% end %>

  <section class="profile-meta">
    <ul>
      <li class="img-profile">
        <%= image_tag (@community_topic&.user&.image&.url || "no-image.jpg") %>
      </li>
      <li class="text-meta">
        <h1><%= @community_topic&.user&.name %></h1>
        <p> <%= User.get_province(@community_topic&.user&.residence) %></p>
      </li>
      <li class="text-meta btn-go-to-profile">
        <%= link_to 'プロフィールを見る', user_path(id: @community_topic.user_id), class: 'block-btn' %>
      </li>
    </ul>
  </section>
</div>

<div class="description">
  <%= @community_topic&.description&.gsub(/[\r\n]+/, '<br/>')&.html_safe %>
</div>

<section class="messages-community">
  <div id="form-messages-community">
    <ul class="community-message-list" data-behavior='community_messages' data-community-room-id=<%= @community_room.id %>>
      <% @messages.each_with_index do |message, i| %>
        <% is_after = i > 0 && @messages[i - 1].user_id === message.user_id %>
        <%= render partial: 'community_messages/message',
                   locals: { message: message, is_after: is_after, community_room: @community_room } %>
      <% end %>
    </ul>
  </div>
  <% if @user_join_community.include?(current_user) || current_user == @community_topic&.community.user %>
    <div class="compose-box">
      <%= form_for CommunityMessage.new, url: community_room_community_messages_path(community_room_id: @community_room&.id), remote: true,
        html: { class: 'form-chat-topic', method: :post, id: 'new-community-message' } do |f| %>

        <div class="form-chat-input">
          <%= f.text_area :body, rows: 10, autofocus: true, class: "message_body" %>
        </div>
        <%= hidden_field_tag "community_topic_id", @community_topic.id %>
        <div class="group-button">
          <div class="btn-image">
            <div class="image-field">
              <%= f.file_field :image, id: "image_field_1", class: 'image_field', data: {index: 1} %>
              <span id="remove_1"
                    class="remove <%= 'hidden' unless f.object.image.exists? %>"
                    data-index="1">
                <i class="fa fa-times-circle" aria-hidden="true"></i>
              </span>
              <div class="preview-image" data-index="1">
                <% img_url =(f.object.image.url == "/images/original/missing.png" || f.object.image.nil?) ? "/images/original/camera.png" : f.object.image.url %>
                <%= image_tag img_url, class: 'preview', id: "preview_img_1" %>
              </div>
            </div>
          </div>
          <%= f.submit "メッセージを送る", class: "btn-submit-msg-topic" %>
        </div>

      <% end %>
    </div>
  <% else %>
    <div class="btn-create">
      <%= link_to "参加する", "javascript:void(0)", id: "btn-join-group", class: "btn-create-community-topic" %>
    </div>
    <%= render "communities/modal_join_community", community: @community_topic&.community %>
  <% end %>
</section>